import 'package:flutter/material.dart';
import 'model/art.dart';

var DUMMY_DATA = [
  Art(
      "1",
      "Mona Lisa, La Gioconda",
      "1",
      "f",
      "https://cs1.livemaster.ru/storage/c0/7b/e335a5db05bd9a854e828041a4dt--kartiny-i-panno-mona-liza-leonardo-da-vinchi-ruchnaya-kopiya-.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "2",
      "Mona Lisa, La Gioconda",
      "2",
      "f",
      "https://jvern.club/images/artlib_gallery-50820-o.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "3",
      "Mona Lisa, La Gioconda",
      "3",
      "f",
      "https://s.mediasole.ru/images/631/631142/30.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "4",
      "Mona Lisa, La Gioconda",
      "4",
      "f",
      "https://svoimi-rukami2.ru/wp-content/uploads/a/3/b/a3b2549fa6a9eaa1a27d56a2ea6dc3a1.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "5",
      "Mona Lisa, La Gioconda",
      "5",
      "f",
      "https://3.404content.com/1/CF/5F/615667476899562669/fullsize.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "6",
      "Mona Lisa, La Gioconda",
      "6",
      "f",
      "https://regnum.ru/uploads/pictures/news/2016/03/17/regnum_picture_1458239388189692_normal.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "7",
      "Mona Lisa, La Gioconda",
      "7",
      "f",
      "https://litrekon.ru/wp-content/uploads/2021/08/kartina-vasnecova-bayan.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "8",
      "Mona Lisa, La Gioconda",
      "8",
      "f",
      "https://kunstru.ru/wp-content/uploads/2019/05/carevna-liagushka-vasnecov.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art("8", "Mona Lisa, La Gioconda", "9", "f",
      "https://proza.ru/pics/2021/03/20/1871.jpg", "", "", "", "", "", "", ""),
  Art(
      "10",
      "Mona Lisa, La Gioconda",
      "10",
      "f",
      "https://cameralabs.org/media/lab16/post/06-16/15-1/hudozhnik-Mihail-Vrubel_31.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "11",
      "Mona Lisa, La Gioconda",
      "11",
      "f",
      "https://artrue.ru/wp-content/uploads/2016/05/vinogradniki.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "12",
      "Mona Lisa, La Gioconda",
      "12",
      "f",
      "https://cs1.livemaster.ru/storage/c0/7b/e335a5db05bd9a854e828041a4dt--kartiny-i-panno-mona-liza-leonardo-da-vinchi-ruchnaya-kopiya-.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "13",
      "Mona Lisa, La Gioconda",
      "13",
      "f",
      "https://jvern.club/images/artlib_gallery-50820-o.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "14",
      "Mona Lisa, La Gioconda",
      "14",
      "f",
      "https://s.mediasole.ru/images/631/631142/30.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "15",
      "Mona Lisa, La Gioconda",
      "15",
      "f",
      "https://svoimi-rukami2.ru/wp-content/uploads/a/3/b/a3b2549fa6a9eaa1a27d56a2ea6dc3a1.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "16",
      "Mona Lisa, La Gioconda",
      "16",
      "f",
      "https://3.404content.com/1/CF/5F/615667476899562669/fullsize.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "17",
      "Mona Lisa, La Gioconda",
      "17",
      "f",
      "https://regnum.ru/uploads/pictures/news/2016/03/17/regnum_picture_1458239388189692_normal.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "18",
      "Mona Lisa, La Gioconda",
      "18",
      "f",
      "https://litrekon.ru/wp-content/uploads/2021/08/kartina-vasnecova-bayan.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "19",
      "Mona Lisa, La Gioconda",
      "19",
      "f",
      "https://kunstru.ru/wp-content/uploads/2019/05/carevna-liagushka-vasnecov.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art("20", "Mona Lisa, La Gioconda", "20", "f",
      "https://proza.ru/pics/2021/03/20/1871.jpg", "", "", "", "", "", "", ""),
  Art(
      "21",
      "Mona Lisa, La Gioconda",
      "21",
      "f",
      "https://cameralabs.org/media/lab16/post/06-16/15-1/hudozhnik-Mihail-Vrubel_31.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "22",
      "Mona Lisa, La Gioconda",
      "22",
      "f",
      "https://artrue.ru/wp-content/uploads/2016/05/vinogradniki.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
  Art(
      "23",
      "Mona Lisa, La Gioconda",
      "23",
      "f",
      "https://cs1.livemaster.ru/storage/c0/7b/e335a5db05bd9a854e828041a4dt--kartiny-i-panno-mona-liza-leonardo-da-vinchi-ruchnaya-kopiya-.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      ""),
];
